# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(829, 430)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 161, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(480, 20, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(630, 20, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(730, 20, 61, 16))
        self.label_6.setObjectName("label_6")
        self.save_button = QtWidgets.QPushButton(parent=Dialog)
        self.save_button.setGeometry(QtCore.QRect(30, 270, 251, 51))
        self.save_button.setObjectName("save_button")
        self.cancel_button = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(520, 270, 231, 51))
        self.cancel_button.setObjectName("cancel_button")
        self.name_input = QtWidgets.QLineEdit(parent=Dialog)
        self.name_input.setGeometry(QtCore.QRect(20, 50, 111, 31))
        self.name_input.setObjectName("name_input")
        self.roasting_input = QtWidgets.QLineEdit(parent=Dialog)
        self.roasting_input.setGeometry(QtCore.QRect(170, 50, 113, 31))
        self.roasting_input.setObjectName("roasting_input")
        self.type_input = QtWidgets.QLineEdit(parent=Dialog)
        self.type_input.setGeometry(QtCore.QRect(310, 50, 113, 31))
        self.type_input.setObjectName("type_input")
        self.taste_input = QtWidgets.QLineEdit(parent=Dialog)
        self.taste_input.setGeometry(QtCore.QRect(460, 50, 113, 31))
        self.taste_input.setObjectName("taste_input")
        self.price_input = QtWidgets.QLineEdit(parent=Dialog)
        self.price_input.setGeometry(QtCore.QRect(590, 50, 113, 31))
        self.price_input.setObjectName("price_input")
        self.package_input = QtWidgets.QLineEdit(parent=Dialog)
        self.package_input.setGeometry(QtCore.QRect(710, 50, 113, 31))
        self.package_input.setObjectName("package_input")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.label_3.setText(_translate("Dialog", "Тип"))
        self.label_4.setText(_translate("Dialog", "Описание вкуса"))
        self.label_5.setText(_translate("Dialog", "Цена"))
        self.label_6.setText(_translate("Dialog", "Упаковка"))
        self.save_button.setText(_translate("Dialog", "Сохранить"))
        self.cancel_button.setText(_translate("Dialog", "Отменить"))
